/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDemandasRouteImport } from './routes/_authenticated/demandas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated/apps'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProcedimentosIndexRouteImport } from './routes/_authenticated/procedimentos.index'
import { Route as AuthenticatedNoticiasIndexRouteImport } from './routes/_authenticated/noticias.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedProcedimentosIdRouteImport } from './routes/_authenticated/procedimentos.$id'
import { Route as AuthenticatedNoticiasIdRouteImport } from './routes/_authenticated/noticias.$id'
import { Route as AuthenticatedAdminUsuariosNovoRouteImport } from './routes/_authenticated/admin.usuarios.novo'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemandasRoute = AuthenticatedDemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProcedimentosIndexRoute =
  AuthenticatedProcedimentosIndexRouteImport.update({
    id: '/procedimentos/',
    path: '/procedimentos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNoticiasIndexRoute =
  AuthenticatedNoticiasIndexRouteImport.update({
    id: '/noticias/',
    path: '/noticias/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedProcedimentosIdRoute =
  AuthenticatedProcedimentosIdRouteImport.update({
    id: '/procedimentos/$id',
    path: '/procedimentos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNoticiasIdRoute = AuthenticatedNoticiasIdRouteImport.update({
  id: '/noticias/$id',
  path: '/noticias/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsuariosNovoRoute =
  AuthenticatedAdminUsuariosNovoRouteImport.update({
    id: '/usuarios/novo',
    path: '/usuarios/novo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/apps': typeof AuthenticatedAppsRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandas': typeof AuthenticatedDemandasRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/noticias/$id': typeof AuthenticatedNoticiasIdRoute
  '/procedimentos/$id': typeof AuthenticatedProcedimentosIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/noticias/': typeof AuthenticatedNoticiasIndexRoute
  '/procedimentos/': typeof AuthenticatedProcedimentosIndexRoute
  '/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandas': typeof AuthenticatedDemandasRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/noticias/$id': typeof AuthenticatedNoticiasIdRoute
  '/procedimentos/$id': typeof AuthenticatedProcedimentosIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/noticias': typeof AuthenticatedNoticiasIndexRoute
  '/procedimentos': typeof AuthenticatedProcedimentosIndexRoute
  '/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/apps': typeof AuthenticatedAppsRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demandas': typeof AuthenticatedDemandasRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/noticias/$id': typeof AuthenticatedNoticiasIdRoute
  '/_authenticated/procedimentos/$id': typeof AuthenticatedProcedimentosIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/noticias/': typeof AuthenticatedNoticiasIndexRoute
  '/_authenticated/procedimentos/': typeof AuthenticatedProcedimentosIndexRoute
  '/_authenticated/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/apps'
    | '/calendario'
    | '/dashboard'
    | '/demandas'
    | '/documentos'
    | '/empresas'
    | '/noticias/$id'
    | '/procedimentos/$id'
    | '/admin/'
    | '/noticias/'
    | '/procedimentos/'
    | '/admin/usuarios/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/apps'
    | '/calendario'
    | '/dashboard'
    | '/demandas'
    | '/documentos'
    | '/empresas'
    | '/noticias/$id'
    | '/procedimentos/$id'
    | '/admin'
    | '/noticias'
    | '/procedimentos'
    | '/admin/usuarios/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/apps'
    | '/_authenticated/calendario'
    | '/_authenticated/dashboard'
    | '/_authenticated/demandas'
    | '/_authenticated/documentos'
    | '/_authenticated/empresas'
    | '/_authenticated/noticias/$id'
    | '/_authenticated/procedimentos/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/noticias/'
    | '/_authenticated/procedimentos/'
    | '/_authenticated/admin/usuarios/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demandas': {
      id: '/_authenticated/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof AuthenticatedDemandasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/procedimentos/': {
      id: '/_authenticated/procedimentos/'
      path: '/procedimentos'
      fullPath: '/procedimentos/'
      preLoaderRoute: typeof AuthenticatedProcedimentosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/noticias/': {
      id: '/_authenticated/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof AuthenticatedNoticiasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/procedimentos/$id': {
      id: '/_authenticated/procedimentos/$id'
      path: '/procedimentos/$id'
      fullPath: '/procedimentos/$id'
      preLoaderRoute: typeof AuthenticatedProcedimentosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/noticias/$id': {
      id: '/_authenticated/noticias/$id'
      path: '/noticias/$id'
      fullPath: '/noticias/$id'
      preLoaderRoute: typeof AuthenticatedNoticiasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios/novo': {
      id: '/_authenticated/admin/usuarios/novo'
      path: '/usuarios/novo'
      fullPath: '/admin/usuarios/novo'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUsuariosNovoRoute: typeof AuthenticatedAdminUsuariosNovoRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminUsuariosNovoRoute: AuthenticatedAdminUsuariosNovoRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemandasRoute: typeof AuthenticatedDemandasRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedNoticiasIdRoute: typeof AuthenticatedNoticiasIdRoute
  AuthenticatedProcedimentosIdRoute: typeof AuthenticatedProcedimentosIdRoute
  AuthenticatedNoticiasIndexRoute: typeof AuthenticatedNoticiasIndexRoute
  AuthenticatedProcedimentosIndexRoute: typeof AuthenticatedProcedimentosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppsRoute: AuthenticatedAppsRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemandasRoute: AuthenticatedDemandasRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedNoticiasIdRoute: AuthenticatedNoticiasIdRoute,
  AuthenticatedProcedimentosIdRoute: AuthenticatedProcedimentosIdRoute,
  AuthenticatedNoticiasIndexRoute: AuthenticatedNoticiasIndexRoute,
  AuthenticatedProcedimentosIndexRoute: AuthenticatedProcedimentosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
